version: '3'
services:
  reverse:
    container_name: reverse
    image: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./production.conf:/etc/nginx/conf.d/default.conf
      - ./production-site:/usr/share/nginx/html
      - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/jquiro12.tk/fullchain.pem:/etc/letsencrypt/live/jquiro12.tk/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/jquiro12.tk/privkey.pem:/etc/letsencrypt/live/jquiro12.tk/privkey.pem

    depends_on:
      - flask-app
  
  flask-app:
    container_name: flask-app
    restart: always
    build: ./back-end/app
    ports:
      - 5000:5000
    depends_on:
      - mongo-server

  mongo-server:
    container_name: mongo-server
    image: mongo
    volumes:
      - ./mongo_data:/data/db
    ports:
      - 27017:27017
    restart: always