version: '3'
services:

  web:
    image: flask-mongodb-backend
    build: ./app
    command: python3.6 app.py
    ports:
      - "5000:5000"
    depends_on:
      - "mongo"
  
  mongo:
    image: "mongo"
    ports: 
      - "27017:27017"
