version: '3'
services:
  reverse:
    container_name: reverse
    image: nginx
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    restart: always
    volumes:
      - ./server_config/nginx_config:/etc/nginx
      - ./server_config/SSL:/etc/ssl/private
    depends_on:
      - flask-app

  flask-app:
    container_name: flask-app
    restart: always
    build: ./app
    ports:
      - 5000:5000
    depends_on:
      - mongo-server

  mongo-server:
    container_name: mongo-server
    image: mongo
    volumes:
      - ./mongo_data:/data/db
    ports:
      - 27017:27017
    restart: always
