version: '1'
services:
  web:
    image: docker-node-express-mongoapp
    build: ./app
    command: node index.js
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - "mongo"
  
  mongo:
    image: "mongo"
    ports:
      -"27017:27017"
  
  adminmongo:
    image: "mrvautin/adminmongo"
    ports:
      - "1234:1234"